### ISSUE TITLE
3강 MySql 설정

### ISSUE THREAD

**Issue by j2ong** [j2ong/Spring_Boot_Blog#3]
## MySQL 한글 설정
- my.ini 파일
- MySQL 재시작
```
[client]
default-character-set=utf8

[mysql]
default-character-set=utf8

[mysqld]
collation-server = utf8_unicode_ci
init-connect='SET NAMES utf8'
init_connect='SET collation_connection = utf8_general_ci'
character-set-server=utf8
```

## 한글 설정 확인
쿼리창에
`show variables like 'c%';`

## 사용자 생성 및 권한 주기 및 DB 생성
쿼리창에
```
create user '유저이름'@'%' identified by '비밀번호';
GRANT ALL PRIVILEGES ON *.* TO '유저이름'@'%';
CREATE DATABASE blog CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
use blog;
```

##  MySQL 프로젝트 연결
src/main/resources/application.yml에 (.properties를 yml로 바꾼다.)
``` 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
```
